### ISSUE TITLE
tech debt: turn IgnoredMatch into a dataclass

### ISSUE THREAD

**Issue by agateau-gg** [GitGuardian/ggshield#252]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Anonymous-fox** [comment]
Can I help with this one?

**Comment by agateau-gg** [comment]
> Can I help with this one?

Sure, you are more than welcome to work on this! It's better if you wait until #247 is merged though: turning IgnoredMatch into a dataclass is the continuation of the work started with the rework of the configuration file. It should be merged today hopefully 🤞🏻.

**Comment by Anonymous-fox** [comment]
Can I start working on it now?

**Comment by agateau-gg** [comment]
Yes, you can 👍🏻

**Comment by Anonymous-fox** [comment]
Should I create branch from main?

**Comment by agateau-gg** [comment]
No, it's better if you start from the `iac` branch: the `main` branch does not contain the new configuration code yet.

**Comment by Anonymous-fox** [comment]
Should IgnoredMatch support loading from file with list of secrets? Like this:
```
matches-ignore:
  - 530e5a4a7ea00814db8845dd0cae5efaa4b974a3ce1c76d0384ba715248a5dc1
  - MY_TEST_CREDENTIAL
```

**Comment by agateau-gg** [comment]
No, the v2 configuration file format only supports the syntax where a match is declared as an object with `name` and `match` keys. So this should be supported:

```yaml
# correct
secret:
  ignored-matches:
  - name: some secret
    match: 530e5a4a7ea00814db8845dd0cae5efaa4b974a3ce1c76d0384ba715248a5dc1
  - name: another secret
    match: 559583106f3b760810fcb41d7cb99da6e7d118912cdeca19a57358c4b6a6a627
```

But this should not:

```yaml
# incorrect
secret:
  ignored-matches:
  - 530e5a4a7ea00814db8845dd0cae5efaa4b974a3ce1c76d0384ba715248a5dc1
  - 559583106f3b760810fcb41d7cb99da6e7d118912cdeca19a57358c4b6a6a627
```
