### ISSUE TITLE
Config Error Messages Replace "-" With "_"

### ISSUE THREAD

**Issue by rgajason** [GitGuardian/ggshield#480]
## Environment

- ggshield version: 1.14.3
- Operating system (Linux, macOS, Windows): macOS
- Operating system version: Ventura 13.1
- Python version: 3.10.10

## Describe the bug

The "Unrecognized key in config" error message displays an underscore instead of hyphen when an invalid configuration is present.

Steps to reproduce:

Create an invalid configuration file such as (note `ignored-matches` misspelled):

**`.gitguardian.yml`**
```yaml
version: 2
secret:
  ignore-matches:
    - name: some-secret-i-want-to-ignore
      match: 4f2f11652a0<snip>5ead42463
```

Execute a `git commit` that includes the secret you wish to ignore (with GGShield configured as a pre-commit hook).

Actual result:

Error message:

> Unrecognized key in config: ignore_matches

Note the underscore when the configuration has a hyphen.

Expected result:

Error message:

> Unrecognized key in config: ignore-matches

(hyphen instead of underscore)
